### ISSUE TITLE
Updates to installation options

### ISSUE THREAD

**Issue by NewtonBurger** [Dcarns/raspberrypifullnode#3]
Hi, Thanks for doing this site!

Your instructions worked fine with a pi 3 model B.  I'm using wireless.

I'm running the make step now, but had to make a couple of changes to get it working:

- I pulled [version v0.15.0.1](https://github.com/bitcoin/bitcoin/releases)  (v0.11.2 was no longer available)
- I had to include 
```$ sudo apt-get install libevent-dev```

as discussed [here](https://github.com/bitcoin/bitcoin/issues/6758).

**Comment by Dcarns** [comment]
Thanks for the update. I am no longer maintaining this repo, but I will add your suggestions to be as current as I can.

Glad it was helpful!

**Comment by NewtonBurger** [comment]
Thanks!  Closing issue.
